meson_dist = \
config/default/meson.build \
config/meson.build \
config/mobile/meson.build \
config/standard/meson.build \
config/tiling/meson.build \
data/backgrounds/meson.build \
data/desktop/meson.build \
data/etc/meson.build \
data/favorites/meson.build \
data/flags/meson.build \
data/icons/meson.build \
data/images/meson.build \
data/input_methods/meson.build \
data/tools/meson.build \
data/units/meson.build \
data/session/meson.build \
doc/meson.build \
meson.build \
meson/meson-chmod.sh \
meson/clean_check.sh \
meson/meson_inst.sh \
meson/meson_modules.sh \
meson_options.txt \
po/meson.build \
src/bin/e_fm/meson.build \
src/bin/generated/meson.build \
src/bin/meson.build \
src/modules/appmenu/meson.build \
src/modules/backlight/meson.build \
src/modules/battery/meson.build \
src/modules/bluez4/meson.build \
src/modules/clock/meson.build \
src/modules/conf_applications/meson.build \
src/modules/conf_bindings/meson.build \
src/modules/conf_dialogs/meson.build \
src/modules/conf_display/meson.build \
src/modules/conf_interaction/meson.build \
src/modules/conf_intl/meson.build \
src/modules/conf_menus/meson.build \
src/modules/conf/meson.build \
src/modules/conf_paths/meson.build \
src/modules/conf_performance/meson.build \
src/modules/conf_randr/meson.build \
src/modules/conf_shelves/meson.build \
src/modules/conf_theme/meson.build \
src/modules/conf_window_manipulation/meson.build \
src/modules/conf_window_remembers/meson.build \
src/modules/connman/meson.build \
src/modules/cpufreq/meson.build \
src/modules/everything/meson.build \
src/modules/fileman/meson.build \
src/modules/fileman_opinfo/meson.build \
src/modules/gadman/meson.build \
src/modules/geolocation/meson.build \
src/modules/ibar/meson.build \
src/modules/ibox/meson.build \
src/modules/lokker/meson.build \
src/modules/luncher/meson.build \
src/modules/meson.build \
src/modules/mixer/meson.build \
src/modules/msgbus/meson.build \
src/modules/music-control/meson.build \
src/modules/notification/meson.build \
src/modules/packagekit/meson.build \
src/modules/pager/meson.build \
src/modules/pager_plain/meson.build \
src/modules/quickaccess/meson.build \
src/modules/shot/meson.build \
src/modules/start/meson.build \
src/modules/syscon/meson.build \
src/modules/sysinfo/meson.build \
src/modules/systray/meson.build \
src/modules/tasks/meson.build \
src/modules/teamwork/meson.build \
src/modules/temperature/meson.build \
src/modules/tiling/meson.build \
src/modules/time/meson.build \
src/modules/vkbd/meson.build \
src/modules/winlist/meson.build \
src/modules/wireless/meson.build \
src/modules/wizard/meson.build \
src/modules/wl_buffer/meson.build \
src/modules/wl_desktop_shell/meson.build \
src/modules/wl_drm/meson.build \
src/modules/wl_fb/meson.build \
src/modules/wl_text_input/meson.build \
src/modules/wl_weekeyboard/meson.build \
src/modules/wl_wl/meson.build \
src/modules/wl_x11/meson.build \
src/modules/xkbswitch/meson.build \
src/modules/xwayland/meson.build
