//
// Created by raffaele on 01/05/19.
//

#ifndef E_GADGET_CONVERTIBLE_IIO_SENSOR_ACCELEROMETER_H
#define E_GADGET_CONVERTIBLE_IIO_SENSOR_ACCELEROMETER_H

// Those costants are the possible states for the orientation of the acceleromenter.

#define ACCELEROMETER_ORIENTATION_UNDEFINED "undefined"
#define ACCELEROMETER_ORIENTATION_NORMAL "normal"
#define ACCELEROMETER_ORIENTATION_LEFT "left-up"
#define ACCELEROMETER_ORIENTATION_RIGHT "right-up"
#define ACCELEROMETER_ORIENTATION_BOTTOM "bottom-up"

#endif //E_GADGET_CONVERTIBLE_IIO_SENSOR_ACCELEROMETER_H
